jobs:
  publish:
    secrets:
      gpg_key: ${{ secrets.GPG_KEY }}
      sign_ossrh_gradle_properties: ${{ secrets.SIGN_OSSRH_GRADLE_PROPERTIES }}
    uses: tinkoff-mobile-tech/workflows/.github/workflows/android_lib.publish.yml@v1
name: publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
